Repository MonkeInABox/CITS3403Project, pull requests merged in 2024-04, with the labels that each got.

#34 #33addpoststoprofile closes #33
  __pycache__/config.cpython-311.pyc
  app.db
  app/__pycache__/__init__.cpython-311.pyc
  app/__pycache__/models.cpython-311.pyc
  app/auth/__pycache__/__init__.cpython-311.pyc
  app/auth/__pycache__/forms.cpython-311.pyc
  app/auth/__pycache__/routes.cpython-311.pyc
  app/auth/routes.py
  app/auth/templates/login.html
  app/errors/__pycache__/__init__.cpython-311.pyc
  app/errors/__pycache__/errors.cpython-311.pyc
  app/main/__init__.py
  app/main/__pycache__/__init__.cpython-311.pyc
  app/main/__pycache__/forms.cpython-311.pyc
  app/main/__pycache__/routes.cpython-311.pyc
  app/main/forms.py
  app/main/routes.py
  app/main/templates/_comment.html
  app/main/templates/_post.html
  app/main/templates/heading.html
  app/main/templates/profile.html
  app/models.py
  migrations/__pycache__/env.cpython-311.pyc
  migrations/versions/18a5cf241d96_new_fields_in_user_model.py
  migrations/versions/40c247ce7311_.py
  migrations/versions/569096b872fe_.py
  migrations/versions/6d6f7dcc45b4_.py
  migrations/versions/91b6fe8aaa0c_.py
  migrations/versions/__pycache__/18a5cf241d96_new_fields_in_user_model.cpython-311.pyc
  migrations/versions/__pycache__/40c247ce7311_.cpython-311.pyc
  migrations/versions/__pycache__/4ff127b44058_.cpython-311.pyc
  migrations/versions/__pycache__/569096b872fe_.cpython-311.pyc
  migrations/versions/__pycache__/6d6f7dcc45b4_.cpython-311.pyc
  migrations/versions/__pycache__/91b6fe8aaa0c_.cpython-311.pyc
  migrations/versions/__pycache__/e0d72e92ecb9_.cpython-311.pyc
  migrations/versions/e0d72e92ecb9_.py
  startapp.py
Labels: enhancement

#32 Fixed wrong blueprint being imported. closes #31
  __pycache__/config.cpython-311.pyc
  app.db
  app/__pycache__/__init__.cpython-311.pyc
  app/__pycache__/models.cpython-311.pyc
  app/auth/__pycache__/__init__.cpython-311.pyc
  app/auth/__pycache__/forms.cpython-311.pyc
  app/auth/__pycache__/routes.cpython-311.pyc
  app/auth/routes.py
  app/auth/templates/login.html
  app/errors/__pycache__/__init__.cpython-311.pyc
  app/errors/__pycache__/errors.cpython-311.pyc
  app/main/__init__.py
  app/main/__pycache__/__init__.cpython-311.pyc
  app/main/__pycache__/forms.cpython-311.pyc
  app/main/__pycache__/routes.cpython-311.pyc
  app/main/forms.py
  app/main/routes.py
  app/main/templates/heading.html
  app/models.py
  migrations/__pycache__/env.cpython-311.pyc
  migrations/versions/18a5cf241d96_new_fields_in_user_model.py
  migrations/versions/293e8ec9f6d4_.py
  migrations/versions/40c247ce7311_.py
  migrations/versions/569096b872fe_.py
  migrations/versions/6d6f7dcc45b4_.py
  migrations/versions/__pycache__/18a5cf241d96_new_fields_in_user_model.cpython-311.pyc
  migrations/versions/__pycache__/293e8ec9f6d4_.cpython-311.pyc
  migrations/versions/__pycache__/40c247ce7311_.cpython-311.pyc
  migrations/versions/__pycache__/4ff127b44058_.cpython-311.pyc
  migrations/versions/__pycache__/569096b872fe_.cpython-311.pyc
  migrations/versions/__pycache__/6d6f7dcc45b4_.cpython-311.pyc
  migrations/versions/__pycache__/e0d72e92ecb9_.cpython-311.pyc
  migrations/versions/e0d72e92ecb9_.py
Labels: bug

#36 Captcha added for Validation closes #26
  __pycache__/config.cpython-311.pyc
  app.db
  app/__init__.py
  app/__pycache__/__init__.cpython-311.pyc
  app/__pycache__/models.cpython-311.pyc
  app/auth/__pycache__/forms.cpython-311.pyc
  app/auth/__pycache__/routes.cpython-311.pyc
  app/auth/forms.py
  app/auth/routes.py
  app/auth/templates/_captcha.html
  app/auth/templates/registration.html
  app/main/__pycache__/__init__.cpython-311.pyc
  app/main/__pycache__/forms.cpython-311.pyc
  app/main/__pycache__/routes.cpython-311.pyc
  app/main/routes.py
  app/main/templates/_comment.html
  app/main/templates/_post.html
  app/main/templates/index.html
  app/main/templates/new_comment.html
  app/models.py
  config.py
  requirements.txt
Labels: bug, enhancement

#35 Users can now comment on posts closes #24
  app.db
  app/__pycache__/models.cpython-311.pyc
  app/auth/__pycache__/routes.cpython-311.pyc
  app/main/__pycache__/__init__.cpython-311.pyc
  app/main/__pycache__/forms.cpython-311.pyc
  app/main/__pycache__/routes.cpython-311.pyc
  app/main/routes.py
  app/main/templates/_comment.html
  app/main/templates/_post.html
  app/main/templates/index.html
  app/main/templates/new_comment.html
  app/models.py
Labels: bug, enhancement

#39 Added Logo and Updated Design
  app/auth/templates/login.html
  app/main/templates/_post.html
  app/main/templates/heading.html
  app/main/templates/index.html
  app/static/recollective_logo.png
  app/static/styleguide.css
Labels: enhancement
